stages:
  - mirror_clone

mirror_clone:
  stage: mirror_clone

  before_script:
      - mkdir -p ~/.ssh/
      - echo "$GITHUB_SSH_KEY" | tr -d '\r' > ~/.ssh/id_rsa
      - chmod 700 ~/.ssh/id_rsa
      - eval $(ssh-agent -s)
      - ssh-add ~/.ssh/id_rsa
      - ssh-keygen -y -f ~/.ssh/id_rsa > ~/.ssh/id_rsa.pub
      - cat ~/.ssh/id_rsa.pub
      - ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
      - chmod 644 ~/.ssh/known_hosts
      
      - git config --global user.email "ivreone@gmail.com"
      - git config --global user.name "ivreone"

  script:
    - git remote -v
    - git remote add origin https://gitlab.com/ivreone/mirror_test.git
    - git filter-branch -f --commit-filter 'GIT_AUTHOR_NAME="test"; GIT_AUTHOR_EMAIL="test@example.com"; GIT_COMMITER_NAME="test"; GIT_COMMITTER_EMAIL="test@example.com"; git commit-tree "$@";' HEAD
    - git shortlog -s -n -e
    - git push --mirror git@github.com:ivreone/mirror_test.git
