stages:
  - mirror_clone

mirror_clone:
  stage: mirror_clone

  script:
    - ls  
    - git filter-branch -f --commit-filter 'GIT_AUTHOR_NAME="test"; GIT_AUTHOR_EMAIL="test@example.com"; GIT_COMMITER_NAME="test"; GIT_COMMITTER_EMAIL="test@example.com"; git commit-tree "$@";' HEAD && git push --mirror https://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@github.com/ivreone/mirror_test.git
