stages:
  - mirror_clone

mirror_clone:
  stage: mirror_clone

  script:
    - git clone https://gitlab+deploy-token-561582:UHsTzLiYwdZgTbtqHsDy@gitlab.com/ivreone/mirror_test.git
    - cd mirror_test && git filter-branch -f --commit-filter 'GIT_AUTHOR_NAME="test"; GIT_AUTHOR_EMAIL="test@example.com"; GIT_COMMITER_NAME="test"; GIT_COMMITTER_EMAIL="test@example.com"; git commit-tree "$@";' HEAD && git push https://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@github.com/ivreone/mirror_test.git
